language: generic
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t mrgara/docker-react .

script:
  - docker run -e CI=true mrgara/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-444301266470"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
