language: react.js
dist: xenial
os: linux
services:
  - docker

before_install:
  - docker build -t mrgara/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrgara/docker-react npm run test
